name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        go-version: [ '1.20' ]
        os: [ubuntu-latest, macos-latest]
        libsql-server-release: [libsql-server-v0.24.32]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install sqld
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/tursodatabase/libsql/releases/download/${{ matrix.libsql-server-release }}/libsql-server-installer.sh | sh
          echo "$HOME/.sqld/bin" >> $GITHUB_PATH
          sqld --version

      - name: Start sqld server
        run: |
          sqld &
          while ! curl -s http://localhost:8080/health > /dev/null; do
            echo "Waiting for sqld..."
            sleep 1
          done
          echo "sqld is ready!"

      - name: Build
        run: go build -v ./...

      - name: Test
        env:
          LIBSQL_PRIMARY_URL: "http://localhost:8080"
          LIBSQL_AUTH_TOKEN: ""
        run: go test -v ./...
